version: '3.7'

services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - '6379:6379'
    expose:
      - 6379
    volumes:
     - redis_data:/data
    networks:
      - my-network

  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: /app/docker/wsgi-entrypoint.sh
    ports:
      - 8000:8000
    networks:
      - my-network
    env_file:
      - ./.env

  celery:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: celery-worker
    command: bash -c "cd /app/ && celery -A notification_service worker -l info"
    networks:
      - my-network
    depends_on:
      - redis
      - backend
    env_file:
      - ./.env
    restart: always


volumes:
  redis_data:

networks:
  my-network:
