# Generated by Django 4.0.4 on 2022-04-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailings', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Time create')),
                ('sending_status', models.CharField(choices=[('sent', 'Sent'), ('no sent', 'No sent')], max_length=15, verbose_name='Sending status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='customers.customer')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='mailings.mailing')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('-id',),
            },
        ),
    ]
